# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: all_taken_shelter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61ll_taken_shelter.proto\"\x15\n\x13taken_shelter_query\"/\n\x16taken_shelter_response\x12\x15\n\rtaken_shelter\x18\x01 \x01(\x08\x32Y\n\x11\x41ll_Taken_Shelter\x12\x44\n\x11\x61ll_taken_shelter\x12\x14.taken_shelter_query\x1a\x17.taken_shelter_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'all_taken_shelter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TAKEN_SHELTER_QUERY']._serialized_start=27
  _globals['_TAKEN_SHELTER_QUERY']._serialized_end=48
  _globals['_TAKEN_SHELTER_RESPONSE']._serialized_start=50
  _globals['_TAKEN_SHELTER_RESPONSE']._serialized_end=97
  _globals['_ALL_TAKEN_SHELTER']._serialized_start=99
  _globals['_ALL_TAKEN_SHELTER']._serialized_end=188
# @@protoc_insertion_point(module_scope)
