# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import all_taken_shelter_pb2 as all__taken__shelter__pb2


class All_Taken_ShelterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.all_taken_shelter = channel.unary_unary(
                '/All_Taken_Shelter/all_taken_shelter',
                request_serializer=all__taken__shelter__pb2.taken_shelter_query.SerializeToString,
                response_deserializer=all__taken__shelter__pb2.taken_shelter_response.FromString,
                )


class All_Taken_ShelterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def all_taken_shelter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_All_Taken_ShelterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'all_taken_shelter': grpc.unary_unary_rpc_method_handler(
                    servicer.all_taken_shelter,
                    request_deserializer=all__taken__shelter__pb2.taken_shelter_query.FromString,
                    response_serializer=all__taken__shelter__pb2.taken_shelter_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'All_Taken_Shelter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class All_Taken_Shelter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def all_taken_shelter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/All_Taken_Shelter/all_taken_shelter',
            all__taken__shelter__pb2.taken_shelter_query.SerializeToString,
            all__taken__shelter__pb2.taken_shelter_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
