# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: create_soldier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63reate_soldier.proto\"_\n\x0fsoldier_details\x12\x16\n\x0esoldier_number\x18\x01 \x01(\x03\x12\r\n\x05x_pos\x18\x02 \x01(\x03\x12\r\n\x05y_pos\x18\x03 \x01(\x03\x12\x16\n\x0espeed_capacity\x18\x04 \x01(\x03\"\x1d\n\x0esoldier_output\x12\x0b\n\x03msg\x18\x01 \x01(\t2J\n\x0e\x43reate_Soldier\x12\x38\n\x0f\x63reate_soldiers\x12\x10.soldier_details\x1a\x0f.soldier_output\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'create_soldier_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SOLDIER_DETAILS']._serialized_start=24
  _globals['_SOLDIER_DETAILS']._serialized_end=119
  _globals['_SOLDIER_OUTPUT']._serialized_start=121
  _globals['_SOLDIER_OUTPUT']._serialized_end=150
  _globals['_CREATE_SOLDIER']._serialized_start=152
  _globals['_CREATE_SOLDIER']._serialized_end=226
# @@protoc_insertion_point(module_scope)
