# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import create_soldier_pb2 as create__soldier__pb2


class Create_SoldierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_soldiers = channel.stream_unary(
                '/Create_Soldier/create_soldiers',
                request_serializer=create__soldier__pb2.soldier_details.SerializeToString,
                response_deserializer=create__soldier__pb2.soldier_output.FromString,
                )


class Create_SoldierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_soldiers(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Create_SoldierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_soldiers': grpc.stream_unary_rpc_method_handler(
                    servicer.create_soldiers,
                    request_deserializer=create__soldier__pb2.soldier_details.FromString,
                    response_serializer=create__soldier__pb2.soldier_output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Create_Soldier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Create_Soldier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_soldiers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Create_Soldier/create_soldiers',
            create__soldier__pb2.soldier_details.SerializeToString,
            create__soldier__pb2.soldier_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
