# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import elect_commander_pb2 as elect__commander__pb2


class ElectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.elect_commander = channel.unary_unary(
                '/Elector/elect_commander',
                request_serializer=elect__commander__pb2.request.SerializeToString,
                response_deserializer=elect__commander__pb2.elected_commander.FromString,
                )


class ElectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def elect_commander(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'elect_commander': grpc.unary_unary_rpc_method_handler(
                    servicer.elect_commander,
                    request_deserializer=elect__commander__pb2.request.FromString,
                    response_serializer=elect__commander__pb2.elected_commander.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Elector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Elector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def elect_commander(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Elector/elect_commander',
            elect__commander__pb2.request.SerializeToString,
            elect__commander__pb2.elected_commander.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
