# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: elect_commander.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65lect_commander.proto\"\x18\n\x07request\x12\r\n\x05\x64ummy\x18\x01 \x01(\x03\"a\n\x11\x65lected_commander\x12\x16\n\x0esoldier_number\x18\x01 \x01(\x03\x12\r\n\x05x_pos\x18\x02 \x01(\x03\x12\r\n\x05y_pos\x18\x03 \x01(\x03\x12\x16\n\x0espeed_capacity\x18\x04 \x01(\x03\x32<\n\x07\x45lector\x12\x31\n\x0f\x65lect_commander\x12\x08.request\x1a\x12.elected_commander\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elect_commander_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=25
  _globals['_REQUEST']._serialized_end=49
  _globals['_ELECTED_COMMANDER']._serialized_start=51
  _globals['_ELECTED_COMMANDER']._serialized_end=148
  _globals['_ELECTOR']._serialized_start=150
  _globals['_ELECTOR']._serialized_end=210
# @@protoc_insertion_point(module_scope)
