# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_over.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgame_over.proto\"\x0f\n\rgame_over_req\".\n\x12game_over_response\x12\x18\n\x10\x63lient_game_over\x18\x01 \x01(\x08\x32?\n\tGame_Over\x12\x32\n\tgame_over\x12\x0e.game_over_req\x1a\x13.game_over_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_over_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GAME_OVER_REQ']._serialized_start=19
  _globals['_GAME_OVER_REQ']._serialized_end=34
  _globals['_GAME_OVER_RESPONSE']._serialized_start=36
  _globals['_GAME_OVER_RESPONSE']._serialized_end=82
  _globals['_GAME_OVER']._serialized_start=84
  _globals['_GAME_OVER']._serialized_end=147
# @@protoc_insertion_point(module_scope)
