# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_over_pb2 as game__over__pb2


class Game_OverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.game_over = channel.unary_unary(
                '/Game_Over/game_over',
                request_serializer=game__over__pb2.game_over_req.SerializeToString,
                response_deserializer=game__over__pb2.game_over_response.FromString,
                )


class Game_OverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def game_over(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Game_OverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'game_over': grpc.unary_unary_rpc_method_handler(
                    servicer.game_over,
                    request_deserializer=game__over__pb2.game_over_req.FromString,
                    response_serializer=game__over__pb2.game_over_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Game_Over', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game_Over(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def game_over(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Game_Over/game_over',
            game__over__pb2.game_over_req.SerializeToString,
            game__over__pb2.game_over_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
