# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_start.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10game_start.proto\"\x14\n\x12game_start_request\"\x15\n\x13game_start_response2G\n\nGame_Start\x12\x39\n\nstart_game\x12\x13.game_start_request\x1a\x14.game_start_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_start_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GAME_START_REQUEST']._serialized_start=20
  _globals['_GAME_START_REQUEST']._serialized_end=40
  _globals['_GAME_START_RESPONSE']._serialized_start=42
  _globals['_GAME_START_RESPONSE']._serialized_end=63
  _globals['_GAME_START']._serialized_start=65
  _globals['_GAME_START']._serialized_end=136
# @@protoc_insertion_point(module_scope)
