# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_position.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12get_position.proto\"\x16\n\x14position_all_request\"<\n\x07Soldier\x12\x13\n\x0bsoldier_num\x18\x01 \x01(\x03\x12\r\n\x05x_pos\x18\x02 \x01(\x03\x12\r\n\x05y_pos\x18\x03 \x01(\x03\x32\x43\n\x0cGet_Position\x12\x33\n\x0cget_position\x12\x15.position_all_request\x1a\x08.Soldier\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_position_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POSITION_ALL_REQUEST']._serialized_start=22
  _globals['_POSITION_ALL_REQUEST']._serialized_end=44
  _globals['_SOLDIER']._serialized_start=46
  _globals['_SOLDIER']._serialized_end=106
  _globals['_GET_POSITION']._serialized_start=108
  _globals['_GET_POSITION']._serialized_end=175
# @@protoc_insertion_point(module_scope)
