# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import get_params_client_pb2 as get__params__client__pb2


class Get_Params_ClientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_params_client = channel.unary_unary(
                '/Get_Params_Client/get_params_client',
                request_serializer=get__params__client__pb2.params_request.SerializeToString,
                response_deserializer=get__params__client__pb2.params_response.FromString,
                )


class Get_Params_ClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_params_client(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Get_Params_ClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_params_client': grpc.unary_unary_rpc_method_handler(
                    servicer.get_params_client,
                    request_deserializer=get__params__client__pb2.params_request.FromString,
                    response_serializer=get__params__client__pb2.params_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Get_Params_Client', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Get_Params_Client(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_params_client(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Get_Params_Client/get_params_client',
            get__params__client__pb2.params_request.SerializeToString,
            get__params__client__pb2.params_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
