# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import get_valid_position_pb2 as get__valid__position__pb2


class Get_Valid_PositionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_valid_position = channel.stream_unary(
                '/Get_Valid_Position/get_valid_position',
                request_serializer=get__valid__position__pb2.available_positions.SerializeToString,
                response_deserializer=get__valid__position__pb2.valid_position.FromString,
                )


class Get_Valid_PositionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_valid_position(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Get_Valid_PositionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_valid_position': grpc.stream_unary_rpc_method_handler(
                    servicer.get_valid_position,
                    request_deserializer=get__valid__position__pb2.available_positions.FromString,
                    response_serializer=get__valid__position__pb2.valid_position.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Get_Valid_Position', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Get_Valid_Position(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_valid_position(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Get_Valid_Position/get_valid_position',
            get__valid__position__pb2.available_positions.SerializeToString,
            get__valid__position__pb2.valid_position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
