# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_hyperparameters.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19get_hyperparameters.proto\"\x0f\n\rparam_request\"9\n\x0bhyperparams\x12\t\n\x01N\x18\x01 \x01(\x03\x12\t\n\x01M\x18\x02 \x01(\x03\x12\t\n\x01t\x18\x03 \x01(\x03\x12\t\n\x01T\x18\x04 \x01(\x03\x32\x44\n\x0fGet_HyperParams\x12\x31\n\x0fget_hyperparams\x12\x0e.param_request\x1a\x0c.hyperparams\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_hyperparameters_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PARAM_REQUEST']._serialized_start=29
  _globals['_PARAM_REQUEST']._serialized_end=44
  _globals['_HYPERPARAMS']._serialized_start=46
  _globals['_HYPERPARAMS']._serialized_end=103
  _globals['_GET_HYPERPARAMS']._serialized_start=105
  _globals['_GET_HYPERPARAMS']._serialized_end=173
# @@protoc_insertion_point(module_scope)
