# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import get_position_pb2 as get__position__pb2


class Get_PositionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_position = channel.unary_stream(
                '/Get_Position/get_position',
                request_serializer=get__position__pb2.position_all_request.SerializeToString,
                response_deserializer=get__position__pb2.Soldier.FromString,
                )


class Get_PositionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_position(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Get_PositionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_position': grpc.unary_stream_rpc_method_handler(
                    servicer.get_position,
                    request_deserializer=get__position__pb2.position_all_request.FromString,
                    response_serializer=get__position__pb2.Soldier.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Get_Position', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Get_Position(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_position(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Get_Position/get_position',
            get__position__pb2.position_all_request.SerializeToString,
            get__position__pb2.Soldier.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
