# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_valid_position.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18get_valid_position.proto\"3\n\x13\x61vailable_positions\x12\r\n\x05x_pos\x18\x01 \x01(\x03\x12\r\n\x05y_pos\x18\x02 \x01(\x03\":\n\x0evalid_position\x12\x13\n\x0bvalid_x_pos\x18\x01 \x01(\x03\x12\x13\n\x0bvalid_y_pos\x18\x02 \x01(\x03\x32U\n\x12Get_Valid_Position\x12?\n\x12get_valid_position\x12\x14.available_positions\x1a\x0f.valid_position\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_valid_position_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AVAILABLE_POSITIONS']._serialized_start=28
  _globals['_AVAILABLE_POSITIONS']._serialized_end=79
  _globals['_VALID_POSITION']._serialized_start=81
  _globals['_VALID_POSITION']._serialized_end=139
  _globals['_GET_VALID_POSITION']._serialized_start=141
  _globals['_GET_VALID_POSITION']._serialized_end=226
# @@protoc_insertion_point(module_scope)
