# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: is_valid_position.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17is_valid_position.proto\"7\n\x17soldier_escape_position\x12\r\n\x05x_pos\x18\x01 \x01(\x03\x12\r\n\x05y_pos\x18\x02 \x01(\x03\"\x1f\n\x0cvalid_or_not\x12\x0f\n\x07is_safe\x18\x01 \x01(\x08\x32S\n\x11Is_Valid_Position\x12>\n\x11is_valid_position\x12\x18.soldier_escape_position\x1a\r.valid_or_not\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'is_valid_position_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SOLDIER_ESCAPE_POSITION']._serialized_start=27
  _globals['_SOLDIER_ESCAPE_POSITION']._serialized_end=82
  _globals['_VALID_OR_NOT']._serialized_start=84
  _globals['_VALID_OR_NOT']._serialized_end=115
  _globals['_IS_VALID_POSITION']._serialized_start=117
  _globals['_IS_VALID_POSITION']._serialized_end=200
# @@protoc_insertion_point(module_scope)
