# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import is_valid_position_pb2 as is__valid__position__pb2


class Is_Valid_PositionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.is_valid_position = channel.unary_unary(
                '/Is_Valid_Position/is_valid_position',
                request_serializer=is__valid__position__pb2.soldier_escape_position.SerializeToString,
                response_deserializer=is__valid__position__pb2.valid_or_not.FromString,
                )


class Is_Valid_PositionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def is_valid_position(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Is_Valid_PositionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'is_valid_position': grpc.unary_unary_rpc_method_handler(
                    servicer.is_valid_position,
                    request_deserializer=is__valid__position__pb2.soldier_escape_position.FromString,
                    response_serializer=is__valid__position__pb2.valid_or_not.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Is_Valid_Position', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Is_Valid_Position(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def is_valid_position(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Is_Valid_Position/is_valid_position',
            is__valid__position__pb2.soldier_escape_position.SerializeToString,
            is__valid__position__pb2.valid_or_not.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
