# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: send_commander_index.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asend_commander_index.proto\".\n\x13new_commander_index\x12\x17\n\x0f\x63ommander_index\x18\x01 \x01(\x03\"\x13\n\x11\x63ommander_details2Z\n\x14Send_Commander_Index\x12\x42\n\x14send_commander_index\x12\x14.new_commander_index\x1a\x12.commander_details\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'send_commander_index_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NEW_COMMANDER_INDEX']._serialized_start=30
  _globals['_NEW_COMMANDER_INDEX']._serialized_end=76
  _globals['_COMMANDER_DETAILS']._serialized_start=78
  _globals['_COMMANDER_DETAILS']._serialized_end=97
  _globals['_SEND_COMMANDER_INDEX']._serialized_start=99
  _globals['_SEND_COMMANDER_INDEX']._serialized_end=189
# @@protoc_insertion_point(module_scope)
