# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import send_commander_index_pb2 as send__commander__index__pb2


class Send_Commander_IndexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_commander_index = channel.unary_unary(
                '/Send_Commander_Index/send_commander_index',
                request_serializer=send__commander__index__pb2.new_commander_index.SerializeToString,
                response_deserializer=send__commander__index__pb2.commander_details.FromString,
                )


class Send_Commander_IndexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_commander_index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Send_Commander_IndexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_commander_index': grpc.unary_unary_rpc_method_handler(
                    servicer.send_commander_index,
                    request_deserializer=send__commander__index__pb2.new_commander_index.FromString,
                    response_serializer=send__commander__index__pb2.commander_details.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Send_Commander_Index', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Send_Commander_Index(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_commander_index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Send_Commander_Index/send_commander_index',
            send__commander__index__pb2.new_commander_index.SerializeToString,
            send__commander__index__pb2.commander_details.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
