# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstatus.proto\"$\n\x0estatus_request\x12\x12\n\nsoldier_id\x18\x01 \x01(\x03\" \n\x0fstatus_response\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\x37\n\x06Status\x12-\n\x06status\x12\x0f.status_request\x1a\x10.status_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STATUS_REQUEST']._serialized_start=16
  _globals['_STATUS_REQUEST']._serialized_end=52
  _globals['_STATUS_RESPONSE']._serialized_start=54
  _globals['_STATUS_RESPONSE']._serialized_end=86
  _globals['_STATUS']._serialized_start=88
  _globals['_STATUS']._serialized_end=143
# @@protoc_insertion_point(module_scope)
