# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import status_pb2 as status__pb2


class StatusStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.status = channel.unary_unary(
                '/Status/status',
                request_serializer=status__pb2.status_request.SerializeToString,
                response_deserializer=status__pb2.status_response.FromString,
                )


class StatusServicer(object):
    """Missing associated documentation comment in .proto file."""

    def status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'status': grpc.unary_unary_rpc_method_handler(
                    servicer.status,
                    request_deserializer=status__pb2.status_request.FromString,
                    response_serializer=status__pb2.status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Status', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Status(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Status/status',
            status__pb2.status_request.SerializeToString,
            status__pb2.status_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
