# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import take_shelter_pb2 as take__shelter__pb2


class Take_ShelterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call_take_shelter = channel.unary_unary(
                '/Take_Shelter/call_take_shelter',
                request_serializer=take__shelter__pb2.soldier_pos_details.SerializeToString,
                response_deserializer=take__shelter__pb2.secure_position.FromString,
                )


class Take_ShelterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call_take_shelter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Take_ShelterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call_take_shelter': grpc.unary_unary_rpc_method_handler(
                    servicer.call_take_shelter,
                    request_deserializer=take__shelter__pb2.soldier_pos_details.FromString,
                    response_serializer=take__shelter__pb2.secure_position.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Take_Shelter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Take_Shelter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call_take_shelter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Take_Shelter/call_take_shelter',
            take__shelter__pb2.soldier_pos_details.SerializeToString,
            take__shelter__pb2.secure_position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
