# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: take_shelter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12take_shelter.proto\"7\n\x13soldier_pos_details\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x12\n\n\x02id\x18\x03 \x01(\x03\"5\n\x0fsecure_position\x12\x10\n\x08secure_x\x18\x01 \x01(\x03\x12\x10\n\x08secure_y\x18\x02 \x01(\x03\x32M\n\x0cTake_Shelter\x12=\n\x11\x63\x61ll_take_shelter\x12\x14.soldier_pos_details\x1a\x10.secure_position\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'take_shelter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SOLDIER_POS_DETAILS']._serialized_start=22
  _globals['_SOLDIER_POS_DETAILS']._serialized_end=77
  _globals['_SECURE_POSITION']._serialized_start=79
  _globals['_SECURE_POSITION']._serialized_end=132
  _globals['_TAKE_SHELTER']._serialized_start=134
  _globals['_TAKE_SHELTER']._serialized_end=211
# @@protoc_insertion_point(module_scope)
